### ISSUE TITLE
Cannot find module '../../src/methods/node.js'

### ISSUE THREAD

**Issue by joidegn** [SvelteStack/svelte-query#17]
I'm struggling to get the basic examples of svelte-query to work. A clean sapper or svelte kit app results in this when I import anything from `@sveltestack/svelte-query`. Perhaps some issue with es6 modules vs commonjs but I am not experienced enough to figure out more.

e.g. `import { QueryClient, QueryClientProvider } from '@sveltestack/svelte-query'`

results in 

```
yarn run v1.22.10
warning package.json: No license field
$ sapper dev
• server
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to true, as the next major version will default this option to true.
'QueryClient' and 'QueryClientProvider' are imported from external module '@sveltestack/svelte-query' but never used
• client
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to true, as the next major version will default this option to true.
node:internal/modules/cjs/loader:926
  throw err;
  ^

Error: Cannot find module '../../src/methods/node.js'
Require stack:
- ***/node_modules/@sveltestack/svelte-query/dist/index.js
- ***/__sapper__/dev/server/server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
    at Function.Module._load (node:internal/modules/cjs/loader:768:27)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at ***/node_modules/@sveltestack/svelte-query/dist/index.js:3061:24
    at ***/node_modules/@sveltestack/svelte-query/dist/index.js:2:68
    at Object.<anonymous> (***/node_modules/@sveltestack/svelte-query/dist/index.js:5:2)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '***/@sveltestack/svelte-query/dist/index.js',
    '***/__sapper__/dev/server/server.js'
  ]
}
> Server crashed
• service worker
```

```
node --version
v15.10.0
```

**Comment by arekbal** [comment]
Import it as devDependency. It helped me. Back to different issues.

**Comment by joidegn** [comment]
Yeah that was it. Thanks and sorry for the silly issue.

**Comment by frederikhors** [comment]
Same problem here. Can you help me? I'm on the latest sveltekit@next (71) version. I'm already using svelte-query in devDependencies.

**Comment by arekbal** [comment]
I would suggest to try fully reinstalling it as devDependency:
```sh
npm uninstall svelte-query
npm i svelte-query --save-dev
```
or the equivalent in `yarn`

Sounds **basic** but it could be just like that.
